name: Windows Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip wheel setuptools

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Build with PyInstaller
        shell: pwsh
        run: >
          pyinstaller --noconfirm --clean --windowed --onefile
          --name AvitoPriceAnalyzer
          --icon assets/icon.ico
          --add-data "assets/icon.ico;assets"
          app/main.py

      - name: Package artifact
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path build_out | Out-Null
          Copy-Item -Path dist\AvitoPriceAnalyzer.exe -Destination build_out\
          Copy-Item -Path README.md -Destination build_out\ -ErrorAction SilentlyContinue
          Compress-Archive -Path build_out\* -DestinationPath AvitoPriceAnalyzer_win.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AvitoPriceAnalyzer_win
          path: AvitoPriceAnalyzer_win.zip
